variable "env" {}
variable "tags" {}
variable "subnet_ids" {}
variable "vpc_id" {}
variable "sg_port" {}
variable "ssh_ingress" {}
variable "engine_family" {}
variable "engine" {}
variable "node_type" {}
variable "num_cache_nodes" {}
variable "engine_version" {}